import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/themes/ThemeProvider";
import { ClerkProvider } from "@clerk/nextjs";
import { getFullMongoUser } from "@/lib/helpers/auth";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Vibe Kundli",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {

  const dbUser = await getFullMongoUser();

  // Agar user DB mein nahi hai, ya profile adhoori hai -> seedha Onboarding pe bhejo
  if (!dbUser) {
    redirect("/login")
  }
  if (!dbUser.isProfileComplete) {
    redirect("/onboarding");
  }
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, "font-sans", inter.variable)}
    >
      <body suppressHydrationWarning className="min-h-full flex flex-col">
        <ClerkProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            {children}
          </ThemeProvider>
        </ClerkProvider>

      </body>
    </html>
  );
}
